### ISSUE TITLE
bump/nudge polygons, grab/move individual points

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#79]
**Feature Request**: 
It would be helpful if there were a capability to grab individual points of a polygon and move them (rather than deleting the entire polygon and starting again). 

It would also be useful if the entire polygon could be moved and/or bumped/nudged using arrow keys (suppose it's just a few pixels off).

**Comment by jsbroks** [comment]
Using the select tool you should already be able to click on points to move them. Also if you `ctrl+click` it should add a new point. This feature is a bit buggy and does require improvement.

Since the arrow keys are already used for annotation navigation, the user could `shift+click+drag` to move the entire annotation.

To go even further maybe a `ctrl+c`, `ctrl+v` to create a duplicate of an annotation.

**Comment by matt-deboer** [comment]
Ah, ok; I see that I can move a point by clicking on it.

IMO, it would be more intuitive if the point was shown larger when highlighting over it, and somehow indicated that it was being moved. Something to indicate that you had "grabbed" the point for moving--I wasn't really able to tell that I had grabbed a point, but I could see it move when zoomed in enough...

I'll create a separate feature issue to reflect that.

**Comment by NicksonYap** [comment]
Hi, I've pulled the latest commit and tried to `ctrl+click+drag` however it doesn't work, is it already implemented?

**Comment by azmathmoosa** [comment]
does ctrl+click+drag work? it is not working in latest master.
