### ISSUE TITLE
precreate/cache thumbnails

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#92]
**Enhancement**
I've noticed that on a dataset with multiple pages, each click of the paging controls results in request for many thumbnails--which are all generated on the fly (causing the server to bog down temporarily as all of those images are generated--and many of them thrown away).

Perhaps it would be better to pre-create these thumbnails with filename according to some `version` field on the image_model whenever the particular image is updated; that would allow them to be cached on the server's filesystem and even on the client's browser--if they were fetched according to that individual image_model's version... what do you think?

**Comment by jsbroks** [comment]
I was thinking of creating a `/_thumbnail` inside the datasets directory to save thumbnails on save. Then return them to the users, but this methods wouldn't support caching in the web browser

**Comment by AdanMora** [comment]
@jsbroks  Hi, I want to highlight the importance of this issue, when you have really huge images and hundreds of annotations, the thumbnail loading process blows up the server, other issue is when click an image to make/edit annotations, in the background the thumbnail process is still running, so you cannot use the tool properly, I think the best way is write the thumbnails in the new folder outside of the datasets folder (even write them with the annotation's preview if it is possible).

Thanks.

**Comment by jsbroks** [comment]
@AdanMora which version of the annotator are you using.
This issue you mentioned sounds like is more then just the caching of the annotations. Currently, multiple threading in production is not being handled properly

**Comment by AdanMora** [comment]
I already update my version, so I think I'm using the last one, the problem is that the annotator gets busy calculating always the thumbnails, and for example I have a dataset with images with a huge size more the 3000x5000 pixels, with a lot of annotations per image, example:

![thumbnails](https://user-images.githubusercontent.com/32461935/54378206-19ddb400-4687-11e9-980d-4543034eb8d6.png)

It tries to charge all the thumbnails even if you enter to an image. I made a little patch to save the thumbnails in disk and increase a lot the performance and solves this problem. Above you can see the images already loaded with its thumbnail written on disk while the other images are loading its thumbnail.

**Comment by AdanMora** [comment]
I already update my version, so I think I'm using the last one, the problem is that the annotator gets busy calculating always the thumbnails, and for example I have a dataset with images with a huge size more the 3000x5000 pixels, with a lot of annotations per image, example:

![thumbnails](https://user-images.githubusercontent.com/32461935/54378673-1b5bac00-4688-11e9-931a-07d59952c2b7.png)

It tries to charge all the thumbnails even if you enter to an image. I made a little patch to save the thumbnails in disk and increase a lot the performance and solves this problem. Above you can see the images already loaded with its thumbnail written on disk while the other images are loading its thumbnail.

**Comment by jsbroks** [comment]
@AdanMora 
Would be greatly appreciated if you could put a PR in.

**Comment by AdanMora** [comment]
@jsbroks Ok, I'll make it pretty and clean, then I'll put the PR, thanks.
